apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dep-preempt-nginx
spec:
  replicas: 12
  template:
    metadata:
      labels:
        app: preempt-nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - default-pool
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 80
